### ISSUE TITLE
Documentation build error

### ISSUE THREAD

**Issue by AdamRJensen** [ec-jrc/nrt#28]
When I try and build the documentation locally I get a path error. I suggest putting all the content in a folder called "source".

![image](https://github.com/user-attachments/assets/3cde3a17-33be-4375-bf0f-40472eb2b617)

![image](https://github.com/user-attachments/assets/52e77dd5-7506-4eb4-98c0-166dc466c589)

**Comment by AdamRJensen** [comment]
I encountered a new problem. Please test this locally to see if you get the same. It could be that you need the files to be in a different folder than the make file, thus creating a source folder as suggested before

![image](https://github.com/user-attachments/assets/e878cf7b-9384-40a1-96eb-4faa6247a101)

**Comment by AdamRJensen** [comment]
Note I can't reopen this issue

**Comment by loicdtx** [comment]
I don't have the required OS to test this locally. The `make.bat` file is roughly the same as the one generated by the `sphinx-quickstart --batchfile .` command; so things should be working.

Alternatively you can try invoking `sphinx` more directly by running something like `python -m sphinx -T -b html -d _build/doctrees -D language=en . _build/html` or use docker:

```bash
docker run --rm -it \ 
    -v $(pwd):/workspace \
    -w /workspace \
    ubuntu:22.04 \
    /bin/bash -c "apt-get update && apt-get install -y python3 python3-venv python3-pip build-essential make && python3 -m venv /venv && . /venv/bin/activate && pip install --upgrade pip && pip install .[docs] && make -C docs html"
```

Anyway the build logs are available [here](https://readthedocs.org/projects/nrt/builds/)

**Comment by AdamRJensen** [comment]
I reran it with the most recent changes to main and it seems to work now. Thanks
